=== phobos2390/train_game/quicktype_schema/track_data.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/TrackData",
    "definitions": {
        "TrackData": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Point"
                    }
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Track"
                    }
                },
                "junctions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Junction"
                    }
                },
                "colors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Color"
                    }
                },
                "version": {
                    "type": "string"
                }
            },
            "required": [
                "colors",
                "junctions",
                "points",
                "tracks",
                "version"
            ],
            "title": "TrackData"
        },
        "Color": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "red": {
                    "type": "integer"
                },
                "green": {
                    "type": "integer"
                },
                "blue": {
                    "type": "integer"
                }
            },
            "required": [
                "blue",
                "green",
                "id",
                "red"
            ],
            "title": "Color"
        },
        "Junction": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "parent": {
                    "type": "integer"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "selected": {
                    "type": "integer"
                }
            },
            "required": [
                "children",
                "parent",
                "selected"
            ],
            "title": "Junction"
        },
        "Point": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                }
            },
            "required": [
                "x",
                "y"
            ],
            "title": "Point"
        },
        "Track": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "points": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            },
            "required": [
                "points"
            ],
            "title": "Track"
        }
    }
}

=== phobos2390/train_game/res/other_track_data.json
{
  "points":
  [
    { "x":10, "y":20 },
    { "x":50, "y":20 },

    { "x":10, "y":30 },
    { "x":50, "y":30 },

    { "x":60,  "y":20 },
    { "x":100, "y":20 },

    { "x":110, "y":20 },
    { "x":150, "y":20 },

    { "x":110, "y":30 },
    { "x":150, "y":30 },

    { "x":160, "y":25 },
    { "x":170, "y":25 },
    { "x":180, "y":30 },
    { "x":185, "y":35 },
    { "x":190, "y":45 },
    { "x":190, "y":55 },

    { "x":170, "y":80 },
    { "x":170, "y":300 },

    { "x":180, "y":75 },
    { "x":180, "y":305 },

    { "x":190, "y":65 },
    { "x":190, "y":315 },

    { "x":200, "y":75 },
    { "x":200, "y":305 },

    { "x":210, "y":80 },
    { "x":210, "y":300 },

    { "x":190, "y":325 },
    { "x":190, "y":335 },

    { "x":180, "y":335 },
    { "x":160, "y":310 },
    { "x":140, "y":270 },
    { "x":140, "y":120 },

    { "x":185, "y":345 },
    { "x":185, "y":365 },

    { "x":180, "y":370 },
    { "x":175, "y":385 },
    { "x":165, "y":395 },
    { "x":155, "y":405 },

    { "x":190, "y":370 },
    { "x":195, "y":385 },
    { "x":205, "y":395 },
    { "x":215, "y":405 },

    { "x":155, "y":415 },
    { "x":170, "y":415 },
    { "x":200, "y":415 },
    { "x":215, "y":415 },

    { "x":145, "y":415 },
    { "x":90,  "y":385 },
    { "x":45,  "y":300 },
    { "x":45,  "y":125 },

    { "x":225, "y":415 },
    { "x":250, "y":415 },

    { "x":17, "y":32 }
  ],
  "tracks":
  [
    { "points":[0,1] },
    { "points":[2,3] },
    { "points":[4,5] },
    { "points":[6,7] },
    { "points":[8,9] },
    { "points":[10,11,12,13,14,15] },
    { "points":[16,17] },
    { "points":[18,19] },
    { "points":[20,21] },
    { "points":[22,23] },
    { "points":[24,25] },
    { "points":[26,27] },
    { "points":[28,29,30,31] },
    { "points":[32,33] },
    { "points":[34,35,36,37] },
    { "points":[38,39,40,41] },
    { "points":[42,43,44,45] },
    { "points":[46,47,48,49] },
    { "points":[50,51] }
  ],
  "junctions":
  [
    { "parent": 4,  "children": [1,3], "selected": 1 },
    { "parent": 5,  "children": [6,8], "selected": 0 },
    { "parent": 10, "children": [9,7], "selected": 1 },
    { "parent": 15, "children": [16,18,20,22,24], "selected": 1 },
    { "parent": 26, "children": [17,19,21,23,25], "selected": 1 },
    { "parent": 32, "children": [27,28], "selected": 0 },
    { "parent": 33, "children": [34,38], "selected": 0 },
    { "parent": 46, "children": [42,37], "selected": 0 },
    { "parent": 50, "children": [41,45], "selected": 0 }
  ],
  "colors":
  [
    { "id":"junctions", "red": 255, "green": 255, "blue": 0 },
    { "id":"junctions_unselected", "red": 128, "green": 128, "blue": 128 },
    { "id":"tracks", "red": 200, "green": 200, "blue": 200 },
    { "id":"default", "red": 128, "green": 128, "blue": 128 }
  ],
  "version":"0.1.0"
}
